Initial Patch of Okhttp due to J2ObjC java.security subset limitations
Solves:
okhttp-3.3.1-sources/okhttp3/internal/tls/TrustRootIndex.java:21: error: The import java.security.cert.TrustAnchor cannot be resolved
okhttp-3.3.1-sources/okhttp3/internal/tls/TrustRootIndex.java:71: error: TrustAnchor cannot be resolved to a type
okhttp-3.3.1-sources/okhttp3/internal/tls/TrustRootIndex.java:71: error: TrustAnchor cannot be resolved to a type