Initial Patch of okio due to J2ObjC (and Android) java.nio subset limitations
Solves:
./libs/local_src/okio-1.9.0-sources/okio/Okio.java:172: error: Path cannot be resolved to a type
./libs/local_src/okio-1.9.0-sources/okio/Okio.java:172: error: OpenOption cannot be resolved to a type
./libs/local_src/okio-1.9.0-sources/okio/Okio.java:174: error: Files cannot be resolved
./libs/local_src/okio-1.9.0-sources/okio/Okio.java:191: error: Path cannot be resolved to a type
./libs/local_src/okio-1.9.0-sources/okio/Okio.java:191: error: OpenOption cannot be resolved to a type
./libs/local_src/okio-1.9.0-sources/okio/Okio.java:193: error: Files cannot be resolved